; Last update: 2019/08/20

%ifndef CPSUB64
%define CPSUB64

; ------------------------------------------
; function prototypes
; ------------------------------------------
extern Clearscr
extern CloseFile
extern Crlf
extern ClearBuffer
extern Delay
extern DumpMem
extern DumpCC
extern DumpEflags
extern DumpRegs
extern IsDigit
extern Mvcl
extern FileOpen
extern FileClose
extern FileRead
extern FileWrite
extern ParseDecimal32
extern ParseInteger32
extern ParseDecimal64
extern ParseInteger64
extern ReadChar
extern ReadDec
extern ReadHex
extern ReadInt
extern ReadKey
extern ReadString
extern ReadStr
extern Str_compare
extern Str_copy
extern Str_length
extern StrLength
extern Str_trim
extern Str_ucase
extern WriteBin
extern WriteBinB
extern WriteChar
extern WriteDec
extern WriteHex
extern WriteHexDbl
extern WriteHexB
extern WriteInt
extern WriteString
; ------------------------------------------

%endif
